# Generated by Django 5.1.3 on 2026-05-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='instituto',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='jefe_departamento',
        ),
        migrations.RemoveField(
            model_name='gradoescolar',
            name='nivel_educativo',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='unidad_usuario',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='deleted_by',
        ),
        migrations.AlterModelOptions(
            name='catalogstatus',
            options={'default_permissions': (), 'ordering': ['orden', 'nombre'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='estadopais',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='nivelcompetencia',
            options={'default_permissions': (), 'ordering': ['orden', 'nombre'], 'verbose_name': 'Nivel de competencia', 'verbose_name_plural': 'Niveles de competencia'},
        ),
        migrations.AlterModelOptions(
            name='tipetema',
            options={'default_permissions': (), 'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de tema', 'verbose_name_plural': 'Tipos de tema'},
        ),
        migrations.AlterModelOptions(
            name='tipobloquecontenido',
            options={'default_permissions': (), 'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de bloque de contenido', 'verbose_name_plural': 'Tipos de bloque de contenido'},
        ),
        migrations.AlterModelOptions(
            name='tipoevaluacion',
            options={'default_permissions': (), 'ordering': ['orden', 'nombre'], 'verbose_name': 'Tipo de evaluación', 'verbose_name_plural': 'Tipos de evaluación'},
        ),
        migrations.DeleteModel(
            name='CambioDepartamento',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='GradoEscolar',
        ),
        migrations.DeleteModel(
            name='NivelEducativo',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
