# Generated by Django 5.1.3 on 2026-05-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('texto', models.TextField(blank=True)),
                ('variante', models.CharField(blank=True, max_length=20)),
                ('items', models.JSONField(blank=True, null=True)),
                ('filas', models.JSONField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Bloque de contenido',
                'verbose_name_plural': 'Bloques de contenido',
                'ordering': ['tema', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('imagen', models.ImageField(blank=True, upload_to='capacitacion/cursos/imagenes/')),
                ('banner', models.ImageField(blank=True, upload_to='capacitacion/cursos/banners/')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('puntaje_minimo', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('inscrito_at', models.DateTimeField(auto_now_add=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-inscrito_at'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('horas_teoricas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_practicas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiene_evaluacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_correcta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Opción de pregunta',
                'verbose_name_plural': 'Opciones de pregunta',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['evaluacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('completado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Progreso de tema',
                'verbose_name_plural': 'Progresos de tema',
                'ordering': ['-completado_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('correctas', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('presentado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resultado de evaluación',
                'verbose_name_plural': 'Resultados de evaluación',
                'ordering': ['-presentado_at'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('duracion_estimada', models.CharField(blank=True, max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['modulo', 'orden'],
            },
        ),
    ]
