# Generated by Django 5.1.3 on 2026-05-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0001_initial'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidobloque',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloques', to='catalogos.tipobloquecontenido'),
        ),
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='catalogos.catalogstatus'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='capacitacion.curso'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='catalogos.tipoevaluacion'),
        ),
    ]
