# Generated by Django 5.1.3 on 2026-05-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0002_initial'),
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_inscripcion_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='capacitacion.curso'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='capacitacion.curso'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='capacitacion.modulo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='capacitacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='capacitacion.pregunta'),
        ),
        migrations.AddField(
            model_name='progresotema',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_progresotema_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitacion_resultadoevaluacion_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultadoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='capacitacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='tema',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='capacitacion.modulo'),
        ),
        migrations.AddField(
            model_name='tema',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temas', to='catalogos.tipetema'),
        ),
        migrations.AddField(
            model_name='progresotema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresos', to='capacitacion.tema'),
        ),
        migrations.AddField(
            model_name='contenidobloque',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='capacitacion.tema'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('colaborador', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='modulo',
            unique_together={('curso', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('evaluacion', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='opcionpregunta',
            unique_together={('pregunta', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('modulo', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='progresotema',
            unique_together={('colaborador', 'tema')},
        ),
        migrations.AlterUniqueTogether(
            name='contenidobloque',
            unique_together={('tema', 'orden')},
        ),
    ]
