# Generated by Django 5.1.3 on 2026-05-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidobloque',
            options={'default_permissions': (), 'ordering': ['tema', 'orden'], 'verbose_name': 'Bloque de contenido', 'verbose_name_plural': 'Bloques de contenido'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'default_permissions': (), 'ordering': ['titulo'], 'permissions': [('ver_curso', 'Ver curso'), ('agregar_curso', 'Agregar curso'), ('editar_curso', 'Editar curso'), ('eliminar_curso', 'Eliminar curso')], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'default_permissions': (), 'ordering': ['titulo'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'default_permissions': (), 'ordering': ['-inscrito_at'], 'permissions': [('ver_inscripcion', 'Ver inscripción'), ('agregar_inscripcion', 'Agregar inscripción')], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'default_permissions': (), 'ordering': ['curso', 'orden'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='opcionpregunta',
            options={'default_permissions': (), 'ordering': ['pregunta', 'orden'], 'verbose_name': 'Opción de pregunta', 'verbose_name_plural': 'Opciones de pregunta'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'default_permissions': (), 'ordering': ['evaluacion', 'orden'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='progresotema',
            options={'default_permissions': (), 'ordering': ['-completado_at'], 'verbose_name': 'Progreso de tema', 'verbose_name_plural': 'Progresos de tema'},
        ),
        migrations.AlterModelOptions(
            name='resultadoevaluacion',
            options={'default_permissions': (), 'ordering': ['-presentado_at'], 'verbose_name': 'Resultado de evaluación', 'verbose_name_plural': 'Resultados de evaluación'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'default_permissions': (), 'ordering': ['modulo', 'orden'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
    ]
