# Generated by Django 5.1.3 on 2026-06-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_alter_contenidobloque_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidobloque',
            name='video_archivo',
            field=models.FileField(blank=True, null=True, upload_to='capacitacion/videos/'),
        ),
    ]
