# Generated by Django 5.1.3 on 2026-05-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia', to='sistema.empresa'),
        ),
        migrations.AddField(
            model_name='pestania',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pestanias', to='sistema.modulo'),
        ),
        migrations.AddField(
            model_name='pestania',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='pestanias', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puesto',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='sistema.departamento'),
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('departamento', 'codigo')},
        ),
    ]
