# Generated by Django 5.1.3 on 2026-05-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': [('ver_departamento', 'Ver departamento'), ('agregar_departamento', 'Agregar departamento'), ('editar_departamento', 'Editar departamento'), ('eliminar_departamento', 'Eliminar departamento')], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='dependencia',
            options={'default_permissions': (), 'permissions': [('ver_dependencia', 'Ver dependencia'), ('agregar_dependencia', 'Agregar dependencia'), ('editar_dependencia', 'Editar dependencia'), ('eliminar_dependencia', 'Eliminar dependencia')]},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'default_permissions': (), 'permissions': [('ver_empresa', 'Ver empresa'), ('agregar_empresa', 'Agregar empresa'), ('editar_empresa', 'Editar empresa'), ('eliminar_empresa', 'Eliminar empresa')]},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'default_permissions': (), 'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='pestania',
            options={'default_permissions': (), 'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='puesto',
            options={'default_permissions': (), 'ordering': ['departamento', 'nombre'], 'permissions': [('ver_puesto', 'Ver puesto'), ('agregar_puesto', 'Agregar puesto'), ('editar_puesto', 'Editar puesto'), ('eliminar_puesto', 'Eliminar puesto')], 'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
    ]
