# Generated by Django 5.1.3 on 2026-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_departamento_options_alter_dependencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
