# Generated by Django 5.1.3 on 2026-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_modulo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
