# Generated by Django 5.1.3 on 2026-05-22 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitacion', '0003_initial'),
        ('catalogos', '0002_initial'),
        ('competencias', '0001_initial'),
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competenciacurso',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_cursos', to='competencias.competencia'),
        ),
        migrations.AddField(
            model_name='competenciacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_cursos', to='capacitacion.curso'),
        ),
        migrations.AddField(
            model_name='competenciacurso',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competenciacurso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_cursos', to='catalogos.nivelcompetencia'),
        ),
        migrations.AddField(
            model_name='competenciapuesto',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_puestos', to='competencias.competencia'),
        ),
        migrations.AddField(
            model_name='competenciapuesto',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competenciapuesto',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puesto_competencias', to='catalogos.nivelcompetencia'),
        ),
        migrations.AddField(
            model_name='competenciapuesto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_puestos', to='sistema.puesto'),
        ),
        migrations.AlterUniqueTogether(
            name='competenciacurso',
            unique_together={('competencia', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='competenciapuesto',
            unique_together={('competencia', 'puesto')},
        ),
    ]
