# Generated by Django 5.1.3 on 2026-05-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'default_permissions': (), 'ordering': ['nombre'], 'permissions': [('ver_competencia', 'Ver competencia'), ('agregar_competencia', 'Agregar competencia'), ('editar_competencia', 'Editar competencia'), ('eliminar_competencia', 'Eliminar competencia')], 'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='competenciacurso',
            options={'default_permissions': (), 'ordering': ['competencia', 'curso'], 'permissions': [('ver_competencia_curso', 'Ver competencia por curso'), ('agregar_competencia_curso', 'Agregar competencia por curso'), ('editar_competencia_curso', 'Editar competencia por curso'), ('eliminar_competencia_curso', 'Eliminar competencia por curso')], 'verbose_name': 'Competencia por curso', 'verbose_name_plural': 'Competencias por curso'},
        ),
        migrations.AlterModelOptions(
            name='competenciapuesto',
            options={'default_permissions': (), 'ordering': ['competencia', 'puesto'], 'permissions': [('ver_competencia_puesto', 'Ver competencia por puesto'), ('agregar_competencia_puesto', 'Agregar competencia por puesto'), ('editar_competencia_puesto', 'Editar competencia por puesto'), ('eliminar_competencia_puesto', 'Eliminar competencia por puesto')], 'verbose_name': 'Competencia por puesto', 'verbose_name_plural': 'Competencias por puesto'},
        ),
    ]
