# Generated by Django 5.1.3 on 2026-07-02 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0005_add_video_archivo_to_contenidobloque'),
        ('catalogos', '0003_remove_departamento_instituto_and_more'),
        ('competencias', '0003_alter_competencia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='competencias.competencia')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('nivel_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='catalogos.nivelcompetencia')),
            ],
            options={
                'verbose_name': 'Ruta de aprendizaje',
                'verbose_name_plural': 'Rutas de aprendizaje',
                'ordering': ['competencia', 'nombre'],
                'permissions': [('ver_ruta_aprendizaje', 'Ver ruta de aprendizaje'), ('agregar_ruta_aprendizaje', 'Agregar ruta de aprendizaje'), ('editar_ruta_aprendizaje', 'Editar ruta de aprendizaje'), ('eliminar_ruta_aprendizaje', 'Eliminar ruta de aprendizaje')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RutaAprendizajeCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ruta_cursos', to='capacitacion.curso')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_cursos', to='competencias.rutaaprendizaje')),
            ],
            options={
                'verbose_name': 'Curso en ruta de aprendizaje',
                'verbose_name_plural': 'Cursos en ruta de aprendizaje',
                'ordering': ['ruta', 'orden'],
                'default_permissions': (),
                'unique_together': {('ruta', 'curso'), ('ruta', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='rutaaprendizaje',
            name='cursos',
            field=models.ManyToManyField(related_name='rutas', through='competencias.RutaAprendizajeCurso', to='capacitacion.curso'),
        ),
        migrations.CreateModel(
            name='CompetenciaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias_colaborador', to=settings.AUTH_USER_MODEL)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_colaboradores', to='competencias.competencia')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencia_colaboradores', to='catalogos.nivelcompetencia')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_ganadas', to='capacitacion.inscripcion')),
            ],
            options={
                'verbose_name': 'Competencia de colaborador',
                'verbose_name_plural': 'Competencias de colaboradores',
                'ordering': ['colaborador', 'competencia'],
                'permissions': [('ver_competencia_colaborador', 'Ver competencia de colaborador'), ('editar_competencia_colaborador', 'Editar competencia de colaborador')],
                'default_permissions': (),
                'unique_together': {('colaborador', 'competencia')},
            },
        ),
    ]
