# Generated by Django 5.1.3 on 2026-05-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': (), 'permissions': [('ver_rol', 'Ver rol'), ('agregar_rol', 'Agregar rol'), ('editar_rol', 'Editar rol'), ('eliminar_rol', 'Eliminar rol')]},
        ),
        migrations.AlterModelOptions(
            name='usercustomize',
            options={'default_permissions': (), 'permissions': [('ver_usuario', 'Ver usuario'), ('agregar_usuario', 'Agregar usuario'), ('editar_usuario', 'Editar usuario'), ('eliminar_usuario', 'Eliminar usuario')]},
        ),
    ]
